spring.application.name=smart-teno
server.servlet.context-path=/smt
auth.excluded.urls=${env.auth.excluded.urls}

# Disable request context filter adds it manually at start
spring.web.filter.request-context.enabled=false


# Database Connection Properties
spring.datasource.url=${env.spring.datasource.url}
spring.datasource.username=${env.spring.datasource.username}
spring.datasource.password=${env.spring.datasource.password}
spring.datasource.driver-class-name=${env.spring.datasource.driver-class-name}

# JPA & Hibernate
spring.jpa.database-platform=${env.spring.jpa.database-platform}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.url=${env.spring.data.redis.url}

# JWT
jwt.issuer=${env.jwt.issuer}
jwt.access-token.secret-key=${env.jwt.access-token.secret-key}
jwt.access-token.expiry-in-seconds=${env.jwt.access-token.expiry-in-seconds}
jwt.refresh-token.secret-key=${env.jwt.refresh-token.secret-key}
jwt.refresh-token.expiry-in-seconds=${env.jwt.refresh-token.expiry-in-seconds}

# Cookies Key Prefixes
cookies.key-prefix.access-token=${env.cookies.key-prefix.access-token}
cookies.key-prefix.refresh-token=${env.cookies.key-prefix.refresh-token}
cookies.key-prefix.username=${env.cookies.key-prefix.username}

# Redis Key Prefixes
redis.key-prefix.access-token=${env.redis.key-prefix.access-token}
redis.key-prefix.refresh-token=${env.redis.key-prefix.refresh-token}